version: '2.1'
orbs:
  terraform: 'circleci/terraform@2.1'
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Shantanusri123/Tfvars.git
                ls
          name: GIT Clone TFvars repo
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/plan:
          path: .
          var_file: 'Tfvars/tfvars/dev/s3.tfvars'
      - terraform/apply:
          path: .
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
