version: '2.1'
orbs:
  terraform: 'circleci/terraform@2.1'
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Shantanusri123/Tfvars.git
          name: GIT Clone TFvars repo
      - run:
          name: "LS"
          command: ls
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - run:
          name: "terraform/plan"
          command: terraform plan -var-file "./Tfvars/tfvars/dev/s3.tfvars"
      - run:
          name: "terraform/apply"
          command: terraform apply -var-file "./Tfvars/tfvars/dev/s3.tfvars"
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
