version: 2.1

orbs:
  terraform: 'circleci/terraform@2.1'

parameters:
  environment:
    type: string
    default: ""

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Shantanusri123/Tfvars.git
          name: GIT Clone TFvars repository
      - terraform/init:
          path: .
      - run:
          name: "terraform create workspace"
          command: terraform workspace new <<pipeline.parameters.environment>>
      - run:
          name: "terraform list workspace"
          command: terraform workspace list
      - run:
          name: "terraform select workspace"
          command: terraform workspace select <<pipeline.parameters.environment>>
      - terraform/validate:
          path: 
      - run:
          name: "terraform plan"
          command: terraform plan -var-file "./Tfvars/tfvars/<<pipeline.parameters.environment>>/s3.tfvars"
      - run:
          name: "terraform apply"
          command: terraform apply -auto-approve -var-file "./Tfvars/tfvars/<<pipeline.parameters.environment>>/s3.tfvars"
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle