version: '2.1'
parameters:
  ENV:
    type: string
    default: ""
orbs:
  terraform: 'circleci/terraform@2.1'
workflows:
  deploy_infrastructure:
     jobs:
     - terraform/init:
          path: .
     -  terraform/validate:
          path: .
          checkout: true
          context: terraform
     -  terraform/plan:
           path: .
           checkout: true
           context: terraform
           persist-workspace: true
           var: 'bucket_name1="s3_test" acl_value1="private"'
           requires:
            - terraform/validate
     - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: 'circleci-project-setup'
          requires:
            - terraform/plan
     