version: '2.1'
orbs:
  terraform: 'circleci/terraform@2.1'
workflows:
  deploy_infrastructure:
     jobs:
     - terraform/init:
          path: .
     -  terraform/validate:
          path: .
          checkout: true
          context: terraform
     -  terraform/plan:
           path: .
           checkout: true
           context: terraform
           persist-workspace: true
           requires:
            - terraform/validate
     -  terraform/apply:
          path: .
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: 'circleci-project-setup'
        requires:
     - terraform/apply